export const MODES = {
  DRAG: "DRAG",
  INTERACT: "INTERACT",
  DRAW: "DRAW",
};

export const SHAPE_TYPES = {
  PENCIL: "PENCIL",
  RECTANGLE: "RECTANGLE",
  CIRCLE: "CIRCLE",
  ARROW: "ARROW",
  TEXT: 'TEXT',
  PICTURE: 'PICTURE'
};